version: "2.0"

networks:
  sovryn-network:
    driver: bridge
    name: sovryn-network
    attachable: true
services:
  sovrynnode:
    container_name: sovrynnode
    image: sovrynnode
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SSH_DEPLOY_KEY
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - sovryn-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./accounts.js:/opt/dockerized_app/accounts.js
      - ./telegram.js:/opt/dockerized_app/telegram.js
    environment:
      - NODE_ENV
      - URL
      - HOST
      - WHICHNET
      - KEYPW
      - LIQUIDATOR_ADDRESS
      - LIQUIDATOR_PRIVATE_KEY
      - ROLLOVER_ADDRESS
      - ROLLOVER_PRIVATE_KEY
      - ARBITRAGE_ADDRESS
      - ARBITRAGE_PRIVATE_KEY
      - TELEGRAM_BOT_KEY
    restart: always