#!/bin/bash
export VAULT_NAMESPACE="admin"

#curl --header "X-Vault-Token: $ONETIME_TOKEN" --header "X-Vault-Namespace: admin" $VAULT_ADDR/v1/cubbyhole/private/access-token | jq -r .data.token > /app/secrets/wrapping_token
VAULT_TOKEN=$ONETIME_TOKEN vault read cubbyhole/private/access-token | grep -w token | awk '{print $2}' > /app/secrets/wrapping_token

#WRAPPING_TOKEN=`cat /app/secrets/wrapping_token` && rm -f /app/secrets/wrapping_token && curl --header "X-Vault-Token: $WRAPPING_TOKEN" --header "X-Vault-Namespace: admin" --request POST $VAULT_ADDR/v1/sys/wrapping/unwrap | jq -r .auth.client_token > /app/secrets/vault_token
VAULT_TOKEN=`cat /app/secrets/wrapping_token` vault unwrap | grep -w token | awk '{print $2}' > /app/secrets/vault_token

#VAULT_TOKEN=`cat /app/secrets/vault_token` && rm -f /app/secrets/vault_token && curl --header "X-Vault-Token: $VAULT_TOKEN" --header "X-Vault-Namespace: admin" "$VAULT_ADDR/v1/secret/data/dev" --output /app/secrets/temp
VAULT_TOKEN=`cat /app/secrets/vault_token` vault kv get secret/dev > /app/secrets/temp
ADDR=`cat /app/secrets/temp | grep -w private | awk '{print $2}' | jq -r .address` && sed -i "s/ADDR/$ADDR/g" /app/secrets/accounts.js
PRIVATE=`cat /app/secrets/temp | grep -w private_key | awk '{print $2}'` && sed -i "s/PRIVATE/$PRIVATE/g" /app/secrets/accounts.js
