#!/bin/bash
curl --header "X-Vault-Token: $ONETIME_TOKEN" --header "X-Vault-Namespace: admin" $VAULT_ADDR/v1/cubbyhole/private/access-token | jq -r .data.token > /app/secrets/wrapping_token

WRAPPING_TOKEN=`cat /app/secrets/wrapping_token` && rm -f /app/secrets/wrapping_token && curl --header "X-Vault-Token: $WRAPPING_TOKEN" --header "X-Vault-Namespace: admin" --request POST $VAULT_ADDR/v1/sys/wrapping/unwrap | jq -r .auth.client_token > /app/secrets/vault_token

VAULT_TOKEN=`cat /app/secrets/vault_token` && rm -f /app/secrets/vault_token && curl --header "X-Vault-Token: $VAULT_TOKEN" --header "X-Vault-Namespace: admin" "$VAULT_ADDR/v1/secret/data/dev" --output /app/secrets/temp

ADDR=`cat /app/secrets/temp | jq -r .data.data.private | jq -r .address` && sed -i "s/ADDR/$ADDR/g" /app/secrets/accounts.js
PRIVATE=`cat /app/secrets/temp | jq -r .data.data.private_key` && sed -i "s/PRIVATE/$PRIVATE/g" /app/secrets/accounts.js
